services:
  docling-service:
    build: ./docling-service
    image: hugopg/docling-service

    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
      - DATABASE_URL=${POSTGRES_URL}  # Use POSTGRES_URL for DATABASE_URL
      - VERCEL_API_URL=${VERCEL_API_URL:-http://host.docker.internal:3000}
    volumes:
      - ./docling-service:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-chatbot-network

networks:
  ai-chatbot-network:
    driver: bridge