services:
  docling-service:
    build: ./docling-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    volumes:
      - ./docling-service:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-chatbot-network

networks:
  ai-chatbot-network:
    driver: bridge